// <auto-generated />
namespace GAPT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fc));
        
        string IMigrationMetadata.Id
        {
            get { return "201505191035564_fc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
